# Load seqs ----

library(tidyverse)

cds <- "  1 ATGGGCTTCA GAGTTTGTGT TATTGTCGTC TTCTTGGGTT GTCTTCTTCT
  51 AGTCCCTGAG AAAACAATGG CTCAAGAAAT GAAACGTGCA TCGATCGTTA
101 TCCAAGGAGC TCGACGAGTT TGTGAGACCG ATGAGAACTT TGTCTGTGCG
151 ACATTGGACT GGTGGCCTCA TGACAAGTGC AACTATGACC AATGTCCTTG
201 GGGTTACTCT TCAGTTATCA ATATGGATTT AACGCGTCCC CTTCTTACTA
251 AAGCTATTAA AGCTTTCAAG CCGTTGAGGA TAAGAATTGG TGGTTCGCTG
301 CAAGATCAAG TTATTTACGA CGTAGGAAAT CTCAAAACTC CTTGCCGTCC
351 ATTCCAAAAA ATGAACAGCG GTTTGTTTGG ATTCTCTAAA GGATGCTTGC
401 ACATGAAACG ATGGGACGAG CTCAACAGTT TCCTAACCGC AACCGGAGCG
451 GTAGTGACAT TCGGTTTAAA CGCTTTGCGT GGGAGACACA AACTCCGCGG
501 AAAGGCGTGG GGTGGTGCAT GGGATCACAT AAACACTCAA GATTTCTTAA
551 ACTACACAGT CTCGAAGGGT TACGTTATTG ATTCTTGGGA ATTCGGAAAC
601 GAGCTGAGTG GAAGCGGAGT TGGTGCGAGC GTGAGCGCAG AGCTTTACGG
651 GAAAGACTTG ATTGTACTTA AAGATGTAAT CAACAAAGTT TATAAAAATT
701 CTTGGTTACA CAAGCCTATA CTTGTCGCTC CTGGAGGGTT CTATGAACAA
751 CAATGGTACA CCAAACTTCT TGAAATTTCC GGTCCTAGTG TTGTCGACGT
801 TGTGACTCAT CATATATACA ATCTTGGTTC AGGAAATGAT CCCGCGCTGG
851 TGAAGAAGAT AATGGATCCG AGTTATTTAA GCCAGGTATC AAAAACATTC
901 AAGGACGTGA ACCAGACGAT TCAAGAACAT GGACCGTGGG CTTCTCCTTG
951 GGTTGGAGAA TCTGGTGGAG CTTACAATAG TGGTGGCCGT CATGTTTCTG
1001 ACACATTCAT AGATAGCTTC TGGTATCTAG ATCAGCTTGG AATGTCAGCG
1051 AGACACAACA CTAAAGTTTA CTGCAGACAG ACTTTGGTTG GAGGGTTTTA
1101 CGGCTTGCTC GAAAAGGGAA CGTTTGTTCC AAATCCTGAT TACTATAGCG
1151 CGCTGCTTTG GCATCGTTTA ATGGGAAAAG GGGTTCTTGC GGTGCAGACA
1201 GATGGACCGC CACAGCTACG GGTTTACGCA CATTGTTCAA AAGGAAGAGC
1251 CGGTGTGACA TTGCTACTGA TAAATCTAAG CAATCAATCG GATTTTACGG
1301 TTAGTGTCAG CAATGGCATA AACGTGGTTT TGAATGCGGA ATCAAGGAAG
1351 AAGAAGTCAT TGTTGGATAC TTTAAAAAGA CCATTTTCTT GGATTGGAAG
1401 CAAAGCTTCT GATGGATATT TGAATAGAGA AGAGTATCAT CTGACACCAG
1451 AAAACGGTGT GTTGCGCAGC AAAACAATGG TCTTGAATGG TAAATCGTTA
1501 AAACCGACGG CAACAGGAGA TATCCCGAGC CTTGAACCGG TCCTCCGTAG
1551 TGTGAACTCT CCGCTTAATG TCTTGCCATT GTCGATGTCG TTCATTGTGT
1601 TACCTAATTT TGATGCTTCT GCTTGTTCAT GA"

gene_seq <- " 1 CCAAAATCAA TTAACGAGAA TAAAAAGGAA TTAACGAATA AAAAGTGGTA
  51 GAAAGCTCAT GTTTCAAGAG AAGGTTTTGA TTCATCAACC AAGTTGCACC
101 AACTCCATAT ATATTACCAA AACCAAAATA AATTTACATA TTTGGAAAGA
151 ACATAAATTG GACAGAACAT ATCAAGCATG TAATATACAG AAGCCGACAA
201 ATTGCAAAAT TTACCTAAAC CCCATCTTAC ACCACCGTCA GATTCTGATG
251 TAAGTATTAT CAAAGCTCAA GAACAATCAC ATCATCAGAA TCTAACTTAT
301 ATATCAAAGG TCCAGAATTT TCTCCATTGA AGCTGGATTC TAAGGTCAGT
351 TCTTACTTCT TTATCTCAAT CTGATGATTC CATATCGAAA GTCTTACTTT
401 TTCACTTCAA TTTCAATCTG ATGATTCTAA GATCTTTGAT TCGAGGTCGA
451 TCTCTGATAG TTACTACATG TTTCTGGGTT TATTTATTTT TAATCCATAT
501 AGTAATTAAA AACTCTTATG AGGTTTAATT ATGGTTACTT GAGAATTTGC
551 AATCGTCATC TTTCTTTGAC TCCTATCCAT TTTTTGGTTT TTCCTTTGTT
601 TAATTTCTGT TTCATAATTG TAATTGTAAA TTAACCAAAA CAAATTGATC
651 AGAAACCTTT TTCCTATGGA ATATTTATCA CACGCAAGCC TGTGAGTTGT
701 GACTCTGTAA TCACTTCCTT GTTCTGGTAA TTTCAGTGGT TAAGGCTCTC
751 CTTTTTTCTG ATGTTGTCAG CAAAAGTTAG TTTTTCTTCT TCTTTAATGG
801 GTTAATTACA CCTAAATCTC TGGTTATTAA ACAATCCAGA AAGAAAAAAA
851 GTTTATTCCT TCCTCTATGT ATATAGTTTC ACATGCAAGC ATCACTTGTT
901 TGTTCTGACA AATTGCAGAG TTTTGAGTTC TGTTTTTTTT TTTTTCTAAT
951 GTTTTGTCTT TAAGAAAGTT CTGTTTTTTT TTCTGCAGGA AAGTTATCAA
1001 AAGTTTTGAG AGCTTTGGAT AGTGAAGCTC AAAGAACTAA ACAATGGGCT
1051 TCAGAGTTTG TGTTATTGTC GTCTTCTTGG GTTGTCTTCT TCTAGTCCCT
1101 GAGAAAACAA TGGCTCAAGA AATGAAACGT GCATCGATCG TTATCCAAGG
1151 AGCTCGACGA GTTTGTGAGA CCGATGAGAA CTTTGTCTGT GCGACATTGG
1201 ACTGGTGGCC TCATGACAAG TGCAACTATG ACCAATGTCC TTGGGGTTAC
1251 TCTTCAGTTA TCAATATGGT AATAGCAAAA TAGTAAAGGA TTCACCTTTC
1301 AGTCTCTTCA TAATAACAAT GTCCGCAGTT GCGATAATTT TCTGATCTTT
1351 CCAATGTTTT ACAGGATTTA ACGCGTCCCC TTCTTACTAA AGCTATTAAA
1401 GGTTTGCACC TGGCATACCA AAAATGTTCA TGCCATTGCT TTGTGTGTTC
1451 TTGAATTCTG AAATTTTTAA GGATTTGGAT TTTTGTATTT GCTTAGCTTT
1501 CAAGCCGTTG AGGATAAGAA TTGGTGGTTC GCTGCAAGAT CAAGTTATTT
1551 ACGACGTAGG AAATCTCAAA ACTCCTTGCC GTCCATTCCA AAAAATGAAC
1601 AGCGGTTTGT TTGGATTCTC TAAAGGATGC TTGCACATGA AACGATGGGA
1651 CGAGCTCAAC AGTTTCCTAA CCGCAACCGG GTAAGCTAAT TCACTTTCGG
1701 TTTAGTTTCA TTAACGTTCA CATTTTCCTC TTTTGAAGAA TCTTGAGTTA
1751 GTTGTGTTTG CTTGTTTTTA TCGAGCAGAG CGGTAGTGAC ATTCGGTTTA
1801 AACGCTTTGC GTGGGAGACA CAAACTCCGC GGAAAGGCGT GGGGTGGTGC
1851 ATGGGATCAC ATAAACACTC AAGATTTCTT AAACTACACA GTCTCGAAGG
1901 GTTACGTTAT TGATTCTTGG GAATTCGGTA ACAACAAACA TTTAAAAAGT
1951 CGCCTTCTTT TACTCGGTCT TTTTTCTTAG CTTTCCTTGT TCTCGGTATA
2001 GGAAACGAGC TGAGTGGAAG CGGAGTTGGT GCGAGCGTGA GCGCAGAGCT
2051 TTACGGGAAA GACTTGATTG TACTTAAAGA TGTAATCAAC AAAGTTTATA
2101 AAAATTCTTG GTTACACAAG CCTATACTTG TCGCTCCTGG AGGGTTCTAT
2151 GAACAACAAT GGTACACCAA ACTTCTTGAA ATTTCCGGTC CTAGTGTTGT
2201 CGACGTTGTG ACTCATCATA TATACAATCT TGGTTCAGGT CTGGTTTTGT
2251 ATAATATAAT CAAAATAAAC TCAAAACCAT TACTTATATA TATCATATCT
2301 GAGGAATCAT CTGCCTTCTC TGTTTGAGTC TTGCAGGAAA TGATCCCGCG
2351 CTGGTGAAGA AGATAATGGA TCCGAGTTAT TTAAGCCAGG TATCAAAAAC
2401 ATTCAAGGAC GTGAACCAGA CGATTCAAGA ACATGGACCG TGGGCTTCTC
2451 CTTGGGTTGG AGAATCTGGT GGAGCTTACA ATAGTGGTGG CCGTCATGTT
2501 TCTGACACAT TCATAGATAG CTTCTGGTAA AACAAAACAA ATATCCATTT
2551 CGGATATCTT GATTTTAGCC CCTGATTTCT ATTACTGAAT GAACTAAAAG
2601 AGGCATCTTT GGATCCAATC TTTTTGAAGG TATCTAGATC AGCTTGGAAT
2651 GTCAGCGAGA CACAACACTA AAGTTTACTG CAGACAGACT TTGGTTGGAG
2701 GGTTTTACGG CTTGCTCGAA AAGGGAACGT TTGTTCCAAA TCCTGATTAC
2751 TATAGGTGAG AGTCCCAAAC AAAATCCGGA CTTTGAAATT TTATGGTTGA
2801 TTGATCTTGA AGTTTTATCT GACTTTTTCC GCCAATCTTT CTCTTTCGGT
2851 CGGGTTTCGG GACAGCGCGC TGCTTTGGCA TCGTTTAATG GGAAAAGGGG
2901 TTCTTGCGGT GCAGACAGAT GGACCGCCAC AGCTACGGGT TTACGCACAT
2951 TGTTCAAAAG GAAGAGTGAG TTGCTCATAT CATCTTTTAT ATCGCAGTTT
3001 CCAAACGTCT TTTTCGGTTA GAGTTTGCTT TAAATGCTTT GGTTTTTTCT
3051 TGGTTTTAGG CCGGTGTGAC ATTGCTACTG ATAAATCTAA GCAATCAATC
3101 GGATTTTACG GTTAGTGTCA GCAATGGCAT AAACGTGGTT TTGAATGCGG
3151 AATCAAGGAA GAAGAAGTCA TTGTTGGATA CTTTAAAAAG ACCATTTTCT
3201 TGGATTGGAA GCAAAGCTTC TGATGGATAT TTGAATAGAG AAGAGTATCA
3251 TCTGACACCA GAAAACGGTG TGTTGCGCAG CAAAACAATG GTCTTGAATG
3301 GTAAATCGTT AAAACCGACG GCAACAGGAG ATATCCCGAG CCTTGAACCG
3351 GTCCTCCGTA GTGTGAACTC TCCGCTTAAT GTCTTGCCAT TGTCGATGTC
3401 GTTCATTGTG TTACCTAATT TTGATGCTTC TGCTTGTTCA TGATGTTAAT
3451 GGGGTCTCTC TTTGCTTATT GGGAAAAAAT AAATAAAAAT AAAGAATAGT
3501 TGTAATTTTT TTGGTAATTG TATCTAATGC TGGTGATAAA TGTATCATTT
3551 CATATTTCAA TACA"

# reformat ----

reformat_seq <- function(string) {
  str_extract_all(string, "\\w") %>% 
    unlist() %>%
    str_extract_all("[A-Z]") %>%
    unlist() %>% str_flatten()
}

reformatted_cds <- reformat_seq(cds)
str_count(reformatted_cds) # correct

coding_regions <- "coding_region	 	1044-1268	 		 		 
coding_region	 	1365-1401	 		 		 
coding_region	 	1497-1680	 		 		 
coding_region	 	1779-1927	 		 		 
coding_region	 	2002-2238	 		 		 
coding_region	 	2337-2526	 		 		 
coding_region	 	2630-2755	 		 		 
coding_region	 	2866-2965	 		 		 
coding_region	 	3060-3443	 	"

coding_regions2 <- "1888,2181,2284,2332,2493,2941" 

formatted_cdrs <- coding_regions %>%
  str_extract_all("([^0-9]|^)[0-9]+") %>%
  unlist() %>%
  str_extract_all("[0-9]+")

formatted_cdrs2 <- formatted_cdrs[2:(length(formatted_cdrs)-1)]

starts <- formatted_cdrs2[1:length(formatted_cdrs)%%2!=0] %>%
  map(as.numeric) %>%
  purrr::discard(function(x) identical(x, numeric(0)))

ends <- formatted_cdrs2[1:length(formatted_cdrs)%%2==0] %>%
  map(as.numeric) %>%
  purrr::discard(function(x) identical(x, numeric(0)))

starts
ends

gene_seq_f <- reformat_seq(gene_seq) 

prefixes <- list()

for(i in seq_along(starts)) {
  prefixes[[i]] <- str_sub(gene_seq_f, start=starts[[i]]-8, end=starts[[i]])
}

prefixes

suffixes <- list()

for(i in seq_along(ends)) {
  suffixes[[i]] <- str_sub(gene_seq_f, start=ends[[i]], end=ends[[i]]+7)
}

suffixes

search_sequences <- map2(prefixes, suffixes, str_c)

ips <- reformatted_cds %>% str_locate_all(unlist(prefixes))

ips <- map(ips, ~`[[`(.,2)) %>% unlist()

s <- "abcdefghijk"

original_length <- str_count(reformatted_cds)
insert_dot <- function(string, insert_point) {
  output <- str_c(str_sub(string, start=1, end = insert_point), ".", str_sub(string, start=insert_point+1, end=str_count(string)))
  output
}

insert_dot(s, 3)

outseq <- reformatted_cds

ips_new <- ips + 0:(length(ips)-1)

for (i in seq_along(ips_new)) {
  outseq <- insert_dot(outseq, ips_new[[i]])
}

outseq

sdots <- map2("\\.", suffixes, str_c)

str_detect(outseq, sdots[[7]])

tibble(outseq, search_sequences, insert_point=list(ips))
